# Load packages
library(Hmisc)
library(plyr)
library(dplyr)
library(tidyverse)
library(magrittr)
library(readr)
library(httr)
library(lubridate)
library(sjlabelled)
library(janitor)
library(RColorBrewer)
library(wesanderson)
library(ggrepel)
library(arsenal) 
library(ggbeeswarm)
library(wordcloud2)
library(readxl)
library(viridis)
library(naniar)
library(ComplexUpset)
library(gridExtra)
library(tm)
library(countrycode)
library(ggstatsplot)
library(GGally)
library(paletteer)

#Functions
count_comp <- function(x) sum(as.numeric(x))